// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGdReLQ995_MhCH7AjUqapfMw4kPADhWQ',
    appId: '1:208848172830:web:6576776512939cbf0bbb0f',
    messagingSenderId: '208848172830',
    projectId: 'camara-2001',
    authDomain: 'camara-2001.firebaseapp.com',
    storageBucket: 'camara-2001.firebasestorage.app',
    measurementId: 'G-H8SBFGS73C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Hb_x5jtDmEcjOGwwTwmJ9J6MYnjp48E',
    appId: '1:208848172830:android:746739a14db72e5a0bbb0f',
    messagingSenderId: '208848172830',
    projectId: 'camara-2001',
    storageBucket: 'camara-2001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAneV1uAMaWi6bFF_WQfa-l5C4CTXKZvXQ',
    appId: '1:208848172830:ios:30c3eae180f0916e0bbb0f',
    messagingSenderId: '208848172830',
    projectId: 'camara-2001',
    storageBucket: 'camara-2001.firebasestorage.app',
    iosBundleId: 'com.example.maGuinee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAneV1uAMaWi6bFF_WQfa-l5C4CTXKZvXQ',
    appId: '1:208848172830:ios:30c3eae180f0916e0bbb0f',
    messagingSenderId: '208848172830',
    projectId: 'camara-2001',
    storageBucket: 'camara-2001.firebasestorage.app',
    iosBundleId: 'com.example.maGuinee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZy4vW_L1UBE9nAtyHHWr-AkRFKg6mCZs',
    appId: '1:208848172830:web:dcbb0ec8ca8d276f0bbb0f',
    messagingSenderId: '208848172830',
    projectId: 'camara-2001',
    authDomain: 'camara-2001.firebaseapp.com',
    storageBucket: 'camara-2001.firebasestorage.app',
    measurementId: 'G-QZQMX8ZZST',
  );
}
